apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cirrusdb-pv-claim
  labels:
    app: cirrusdb
    tier: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
