version: '3.9'
services:
  # creates database in a container
  cirrusdatabase:
    image: mysql
    platform: linux/amd64
    ports:
      - ${EXTERNALDB_PORT}:${DBPORT}
    volumes:
      - db:/usr/local/mysql
    restart: on-failure:5
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQLDB_ROOT_PASSWORD}"
      MYSQL_USER: "${MYSQLDB_USER}"
      MYSQL_PASSWORD: "${MYSQLDB_PASSWORD}"
      MYSQL_DATABASE: "${MYSQLDB_DATABASE}"
      MYSQL_ROOT_HOST: '%'

  # gateway service routes users
  gateway:
    image: laxwalrus/capstone-gateway:v1
    depends_on:
      - cirrusdatabase
    restart: on-failure:5
    environment:
      - "SERVICE_HOST=${SERVICE_HOST}"


    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
    
    
  # users service handles account creatation 
  users:
    image: laxwalrus/capstone-users:v1
    ports:
      - ${USER_PORT}:${USER_PORT}
    volumes:
      - sharedvolume:/var/lib/docker/volumes
    depends_on:
      - cirrusdatabase
      - gateway
    restart: on-failure:5
    environment:
      - "USER_PORT=${USER_PORT}" 
      - "DBPORT=${DBPORT}"
      - "MYSQLDB_DATABASE=${MYSQLDB_DATABASE}"
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - "DATABASE_NAME=${DATABASE_NAME}"
      - "MYSQLDB=${MYSQLDB_USER}"
      - "MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}"

  # application/applicants services
  underwriter:
    image: laxwalrus/capstone-underwriter:v1
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}
    volumes:
      - sharedvolume:/var/lib/docker/volumes
    depends_on:
      - cirrusdatabase
      - gateway
    restart: on-failure:5
    environment:
      - "UNDERWRITER_PORT=${USER_PORT}" 
      - "DBPORT=${DBPORT}"
      - "MYSQLDB_DATABASE=${MYSQLDB_DATABASE}"
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - "DATABASE_NAME=${DATABASE_NAME}"
      - "MYSQLDB=${MYSQLDB_USER}"
      - "MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}"

  # handles transactions services
  transaction:
    image: laxwalrus/capstone-transaction:v1
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}
    volumes:
      - sharedvolume:/var/lib/docker/volumes
    depends_on:
      - cirrusdatabase
      - gateway
    restart: on-failure:5   
    environment:
      - "TRANSACTION_PORT=${USER_PORT}" 
      - "DBPORT=${DBPORT}"
      - "MYSQLDB_DATABASE=${MYSQLDB_DATABASE}"
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - "DATABASE_NAME=${DATABASE_NAME}"
      - "MYSQLDB=${MYSQLDB_USER}"
      - "MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}"

  # bank and branches services
  bank:
    image: laxwalrus/capstone-bank:v1
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    volumes:
      - sharedvolume:/var/lib/docker/volumes
    depends_on:
      - cirrusdatabase
      - gateway
    restart: on-failure:5      
    environment:
      - "BANK_PORT=${USER_PORT}" 
      - "DBPORT=${DBPORT}"
      - "MYSQLDB_DATABASE=${MYSQLDB_DATABASE}"
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - "DATABASE_NAME=${DATABASE_NAME}"
      - "MYSQLDB=${MYSQLDB_USER}"
      - "MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}"

  # checking/savings credit accounts service
  account:
    image: laxwalrus/capstone-account
    ports:
      - ${ACCOUNT_PORT}:${ACCOUNT_PORT}
    volumes:
      - sharedvolume:/var/lib/docker/volumes
    depends_on:
      - cirrusdatabase
      - gateway
    restart: on-failure:5      
    environment:
      - "ACCOUNT_PORT=${USER_PORT}" 
      - "DBPORT=${DBPORT}"
      - "MYSQLDB_DATABASE=${MYSQLDB_DATABASE}"
      - "SECRET_KEY=${SECRET_KEY}"
      - "JWT_SECRET_KEY=${JWT_SECRET_KEY}"
      - "DATABASE_NAME=${DATABASE_NAME}"
      - "MYSQLDB=${MYSQLDB_USER}"
      - "MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}"

volumes:
  db:
  sharedvolume:
  
