version: '3.9'
x-aws-vpc: "vpc-03a9e8c3d072bb3eb"


services:
  # creates database in a container
  # cirrusdatabase:
  #   image: mysql
  #   # platform: linux/amd64
  #   ports:
  #     - 3306:3306
  #   # restart: always
  #   environment:
  #     MYSQL_ROOT_PASSWORD: "Password"
  #     MYSQL_USER: "admin"
  #     MYSQL_PASSWORD: "Password"
  #     MYSQL_DATABASE: "alinedb"
  #     MYSQL_ROOT_HOST: '%'

  # gateway service routes users
  gateway:
    image: laxwalrus/capstone-gateway:v1
    environment:
      - SERVICE_HOST=http://172.23.0.1
    ports:
      - 8080:8080
    
  # users service handles account creatation 
  users:
    image: laxwalrus/capstone-users:v1
    ports:
      - 8070:8070
    environment:
      - USER_PORT=8070
      - DBPORT=3306
      - DATABASE_NAME=cirrusbusinessdb.c9ekspidcdn6.us-west-2.rds.amazonaws.com
      - SECRET_KEY=ThisIsAGreatSecretKey!!!
      - JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ95eyJSb2xlIjoiQWRtaW4iLC
      - DBNAME=alinedb
      - MYSQLDB=admin
      - MYSQLDB_PASSWORD=Password

    # volumes:
    #   - ${HOME}/users/logs/:/usr/local/tomcat/logs/
  # application/applicants services
  # underwriter:
  #   image: laxwalrus/capstone-underwriter:v1
  #   ports:
  #     - 8071:8071

  #   depends_on:
  #     - cirrusdatabase
  #   # restart: always
  #   # networks:
  #   #   - my_network
  #   environment:
  #     - "UNDERWRITER_PORT=8071" 
  #     - "DBPORT=3306"
  #     - "MYSQLDB_DATABASE=cirrusdatabase"
  #     - "SECRET_KEY=ThisIsAGreatSecretKey!!!"
  #     - "JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1MTUyMTM5NSwiaWF0"
  #     - "DATABASE_NAME=alinedb"
  #     - "MYSQLDB=admin"
  #     - "MYSQLDB_PASSWORD=Password"

  # # handles transactions services
  # transaction:
  #   image: laxwalrus/capstone-transaction:v1
  #   ports:
  #     - 8073:8073
  #   depends_on:
  #     - cirrusdatabase
  #   # networks:
  #   #   - my_network
  #   # restart: always
  #   environment:
  #     - "TRANSACTION_PORT=8073" 
  #     - "DBPORT=3306"
  #     - "MYSQLDB_DATABASE=cirrusdatabase"
  #     - "SECRET_KEY=ThisIsAGreatSecretKey!!!"
  #     - "JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1MTUyMTM5NSwiaWF0"
  #     - "DATABASE_NAME=alinedb"
  #     - "MYSQLDB=admin"
  #     - "MYSQLDB_PASSWORD=Password"

  # # bank and branches services
  # bank:
  #   image: laxwalrus/capstone-bank:v1
  #   ports:
  #     - 8083:8083

  #   depends_on:
  #     - cirrusdatabase
  #   # networks:
  #   #   - my_network  
  #   # restart: always
  #   environment:
  #     - "BANK_PORT=8083" 
  #     - "DBPORT=3306"
  #     - "MYSQLDB_DATABASE=cirrusdatabase"
  #     - "SECRET_KEY=ThisIsAGreatSecretKey!!!"
  #     - "JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1MTUyMTM5NSwiaWF0"
  #     - "DATABASE_NAME=alinedb"
  #     - "MYSQLDB=admin"
  #     - "MYSQLDB_PASSWORD=Password"

  # # checking/savings credit accounts service
  # account:
  #   image: laxwalrus/capstone-account
  #   ports:
  #     - 8072:8072

  #   depends_on:
  #     - cirrusdatabase
  #   # networks:
  #   #   - my_network    
  #   # restart: always 
  #   environment:
  #     - "ACCOUNT_PORT=8072" 
  #     - "DBPORT=3306"
  #     - "MYSQLDB_DATABASE=cirrusdatabase"
  #     - "SECRET_KEY=ThisIsAGreatSecretKey!!!"
  #     - "JWT_SECRET_KEY=eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY1MTUyMTM5NSwiaWF0"
  #     - "DATABASE_NAME=alinedb"
  #     - "MYSQLDB=admin"
  #     - "MYSQLDB_PASSWORD=Password"
  
# x-aws-cloudformation:
#   Resources:
#     WebappTCP80TargetGroup:
#       Properties:
#         HealthCheckPath: /health
#         Matcher:
#           HttpCode: 200-499

# networks:
#   my_network:
#     ipam:

#       config:
#       - subnet: 172.23.0.1
# volumes:
#   db:

