version: '3.9'
x-aws-vpc: "vpc-03a9e8c3d072bb3eb"
x-aws-loadbalancer: "arn:aws:elasticloadbalancing:us-west-2:421669052337:loadbalancer/net/cirrusLB/ba360e61b151f243"
services:
  # gateway service routes users
  gateway:
    image: laxwalrus/capstone-gateway:AMDv2
    environment:
      - SERVICE_HOST=${CIRRUSLBHOST}
      # - SERVICE_HOST=${SERVICE_HOST}
    ports:
      - ${GATEWAY_PORT}:${GATEWAY_PORT}
  # users service handles account creatation 
  users:
    image: laxwalrus/capstone-users:AMD
    ports:
      - ${USER_PORT}:${USER_PORT}
    environment:
      - USER_PORT=${USER_PORT}
      - DBPORT=${DBPORT}
      - DATABASE_NAME=${AWS_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DBNAME=${MYSQLDB_DATABASE}
      - MYSQLDB=${MYSQLDB_USER}
      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}

  underwriter:
    image: laxwalrus/capstone-underwriter:AMD
    ports:
      - ${UNDERWRITER_PORT}:${UNDERWRITER_PORT}

    environment:
      - UNDERWRITER_PORT=${UNDERWRITER_PORT}
      - DBPORT=${DBPORT}
      - DATABASE_NAME=${AWS_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DBNAME=${MYSQLDB_DATABASE}
      - MYSQLDB=${MYSQLDB_USER}
      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}

   # handles transactions services
  transaction:
    image: laxwalrus/capstone-transaction:AMD
    ports:
      - ${TRANSACTION_PORT}:${TRANSACTION_PORT}

    environment:
      - TRANSACTION_PORT=${TRANSACTION_PORT}
      - DBPORT=${DBPORT}
      - DATABASE_NAME=${AWS_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DBNAME=${MYSQLDB_DATABASE}
      - MYSQLDB=${MYSQLDB_USER}
      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}

   # bank and branches services
  bank:
    image: laxwalrus/capstone-bank:AMD
    ports:
      - ${BANK_PORT}:${BANK_PORT}
    environment:
      - BANK_PORT=${BANK_PORT}
      - DBPORT=${DBPORT}
      - DATABASE_NAME=${AWS_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DBNAME=${MYSQLDB_DATABASE}
      - MYSQLDB=${MYSQLDB_USER}
      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}

 # checking/savings credit accounts service
  account:
    image: laxwalrus/capstone-account:AMDv2
    ports:
      - ${ACCOUNT_PORT}:${ACCOUNT_PORT}
    environment:
      - ACCOUNT_PORT=${ACCOUNT_PORT}
      - DBPORT=${DBPORT}
      - DATABASE_NAME=${AWS_DATABASE}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DBNAME=${MYSQLDB_DATABASE}
      - MYSQLDB=${MYSQLDB_USER}
      - MYSQLDB_PASSWORD=${MYSQLDB_PASSWORD}
