apiVersion: v1
kind: Service
metadata:
  name: gateway

spec:
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
status:
  loadBalancer:
    ingress:
      - ip: 192.168.49.2
