apiVersion: v1
kind: Service
metadata:
  name: transaction

spec:
  type: NodePort
  selector:
    app: transaction
  ports:
    - protocol: TCP
      port: 8073
      targetPort: 8073
      nodePort: 30003
