apiVersion: v1
kind: Service
metadata:
  name: underwriter
  
spec:
  type: NodePort
  selector:
    app: underwriter
  ports:
    - protocol: TCP
      port: 8071
      targetPort: 8071
      nodePort: 30002
